name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_TYPE: UEFI
  FORCE_INSTALL: 1
  HAS_OPENSSL_BUILD: 1
  HAS_OPENSSL_W32BUILD: 0
  WERROR: 1

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Set up networking
        run: |
          sudo -s <<END
          apt-get update
          apt-get install -qq -y dnsmasq-base iproute2 net-tools
          export BRIDGE=br0
          export TAP=tap0
          export NETWORK=10.10.10.0
          export NETMASK=255.255.255.0
          export GATEWAY=10.10.10.1
          export DHCPRANGE=10.10.10.100,10.10.10.254

          # Create bridge
          ip link add $BRIDGE type bridge
          ip link set dev $BRIDGE up
          ip addr add dev $BRIDGE $GATEWAY/$NETMASK

          # Enable forwarding
          sysctl -w net.ipv4.ip_forward=1 > /dev/null 2>&1

          # Create TAP interafce
          ip tuntap add name $TAP mode tap
          ip link set $TAP master $BRIDGE
          ip link set dev tap0 up
          END

      - name: Check networking
        run: sudo ifconfig
