name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_TYPE: UEFI
  FORCE_INSTALL: 1
  HAS_OPENSSL_BUILD: 1
  HAS_OPENSSL_W32BUILD: 0
  WERROR: 1

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Set up networking
        run: |
          sudo -s <<END
          apt-get update
          apt-get install -qq -y dnsmasq-base iproute2 net-tools

          # Create bridge
          ip link add br0 type bridge
          ip link set dev br0 up
          ip addr add dev br0 10.10.10.1/255.255.255.0

          # Enable forwarding
          sysctl -w net.ipv4.ip_forward=1 > /dev/null 2>&1

          # Create TAP interafce
          ip tuntap add name tap0 mode tap
          ip link set tap0 master br0
          ip link set dev tap0 up
          END

      - name: Check networking
        run: sudo ifconfig
